### ISSUE TITLE
Unsatisfied Link Error - Installed Fonts Dir

### ISSUE THREAD

**Issue by adrian-mcmichael** [springmeyer/mapnik-jni#7]
Hi,

I've followed the instructions and am getting the following test error when I build via ant ("ant test"):

`mapnik.Mapnik.getInstalledFontsDir()Ljava/lang/String;
java.lang.UnsatisfiedLinkError: mapnik.Mapnik.getInstalledFontsDir()Ljava/lang/String;
    at mapnik.Mapnik.getInstalledFontsDir(Native Method)
    at mapnik.TestLoadLibrary.testPluginAndFontPaths(TestLoadLibrary.java:28)`

When I try and build a simple Java class to render a map as a png I also get errors that say that the fonts can't be loaded:

`Exception in thread "main" java.lang.RuntimeException: no valid fonts could be loaded in FontSet 'book-fonts' in FontSet at line 9 of 'osm.xml'
        at mapnik.MapDefinition.loadMap(Native Method)
        at Test.main(Test.java:12)`

I am using mapnik branch 2.3.x as 2.0.x appears to no longer compile. The fonts referenced in the font set exist and show in the list when queried with python. Any ideas how I can remedy this? 

Cheers

**Comment by stellaraccident** [comment]
I haven't been involved with this project in several years, but your
symptoms are consistent with not having properly arranged to call
Mapnik.initialize() or having some class loader weirdness going on. Java is
incredibly stupid when it comes to native library linkage and the only 100%
robust way to reference a jar that that loads a native library is to put
that jar on the boot class path (and nowhere else). Try that and make sure
initialize() is getting called and I bet you'll get a bit further.

**Comment by stellaraccident** [comment]
At least, that seems to be the case with the ant setup. Not sure about your
test class. It appears to be calling into the native code. Perhaps
something changed in the way font directories are specified in mapnik? It
used to be hard coded iirc, and perhaps now it is configurable in some way
the jni binding hasn't kept up with?

**Comment by adrian-mcmichael** [comment]
The test class is a replica of the given example from the project readme, wrapped in a Java main method supplied with the XML from mapnik osm data from a working slippymap server.

Since the example contains a call to initialize() as the first line and both the mapnik-jni jar and shared object are on the classpath I suspect you are correct in saying the JNI binding is out of date. Given the lack of any recent activity it seems this project may have died off.

**Comment by springmeyer** [comment]
@adrian-mcmichael - can you open up the log files in `build/testresults/` and post them to https://gist.github.com/ so I can have a look?

@stellaeof - nice to see you here.

**Comment by kaiserpelagic** [comment]
I'm running into the same issue using mapnik 2.3.x. Here is the output of build/testresults/TEST-mapnik.TestLoadLibrary.txt

Testsuite: mapnik.TestLoadLibrary
Tests run: 2, Failures: 0, Errors: 1, Time elapsed: 0.056 sec
------------- Standard Error -----------------
Search path=[/data/mapnik-jni/build/dist, /usr/java/packages/lib/amd64, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]

---

Testcase: testPluginAndFontPaths took 0.008 sec
        Caused an ERROR
mapnik.Mapnik.getInstalledFontsDir()Ljava/lang/String;
java.lang.UnsatisfiedLinkError: mapnik.Mapnik.getInstalledFontsDir()Ljava/lang/String;
        at mapnik.Mapnik.getInstalledFontsDir(Native Method)
        at mapnik.TestLoadLibrary.testPluginAndFontPaths(TestLoadLibrary.java:28)

Testcase: testStaticSettings took 0.034 sec

**Comment by quonn77** [comment]
Hi, I have the same error reported by adrian, but the strange is that if I run several time ant test, some times the test pass and some time (more often) the test fails, As you can see on the attached image 
![selezione_918](https://cloud.githubusercontent.com/assets/9842055/6979769/dfd3c77c-d9e8-11e4-91d3-2aa1dd2e5c0f.png)

TestLayer fails every time because I don't have  postgis installed, but TestLoadLibrary sometimes fails sometimes no.

At the end trying to write a simple application result into:

> Exception in thread "main" java.lang.RuntimeException: no valid fonts could be loaded in

**Comment by quonn77** [comment]
@adrian-mcmichael I have the same problem also for the no valid fonts problem. The workaround is to add after

``` java
Mapnik.initialize()
```

the following code

``` java
//use the path where the fonts are located (see output of mapnik-config --fonts)
FreetypeEngine.registerFonts("/usr/share/fonts/truetype");
```

Now I am able to render a map using the mapnik jni library

I will look into FreetypeEngine code and see if we can automatically register fonts, indeed the code of 
getInstalledFontsDir return right path. if you take a look to mapnikjni.cpp it uses MAPNIK_FONTS_DIR that is configured on the common.mk file with the result of 

```
mapnik-config --fonts
```

This is an abstract of the mapnikjni.cpp file:

``` c++
/*
 * Class:     mapnik_Mapnik
 * Method:    getInstalledFontsDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mapnik_Mapnik_getInstalledFontsDir
  (JNIEnv *env, jclass)
{
#ifndef MAPNIK_FONTS_DIR
    return 0;
#else
    return env->NewStringUTF(MAPNIK_FONTS_DIR);
#endif
}
```

So I think we can automatically let FreetypeEngine discover the right path.
